apiVersion: v1
kind: Service
metadata:
  labels:
    app: yashlanu-pten
  name: yashlani-service-pten
  namespace: default
spec:
  type: NodePort  
  ports:
    - name: http
      protocol: TCP
      port: 3000    
  selector:
    app: yashlanu-pten