apiVersion: v1
kind: Service
metadata:
  labels:
    app: yashlano-course
  name: yashlana-courseni-service
  namespace: default
spec:
  type: NodePort  
  ports:
    - name: http
      protocol: TCP
      port: 3000    
  selector:
    app: yashlano-course