apiVersion: apps/v1
kind: Deployment
metadata:
  name: yashlanu-deployment-prjkt-3
spec:
  selector:
    matchLabels:
      app: yashlanu-node-prjkt
  replicas: 1
  template:
    metadata:
      labels:
        app: yashlanu-node-prjkt
    spec:
      containers:
      - name: nodecontainer
        image: au.icr.io/kirtannamespace/newkirtanimg
        ports:
        - containerPort: 3000